header:
  license:
    spdx-id: MIT
    copyright-owner: Guy Erreich
    content: |
      Copyright (c) 2026 Guy Erreich

      SPDX-License-Identifier: MIT
  paths:
    - src
    - scripts
  paths-ignore:
    - '**/*.yml'
    - '**/*.yaml'
    - '**/*.json'
    - '**/__pycache__/**'
    - '**/py.typed'
