import logging

from auto_semver.config import Config
from auto_semver.config.constants import PR_HIDDEN_MARKER
from auto_semver.gh import GitHubEvent
from auto_semver.semver import SemverLock

logger = logging.getLogger(__package__)


def is_finalized(*, config: Config, event: GitHubEvent) -> bool:
    """
    Check if the PR was generated by the script.

    If the PR is auto generated by the script then we should start the finalization workflow
    else its a bump workflow.

    Args:
        config (Config): Config object.
        event (GitHubEvent): GitHubEvent object.

    """
    logger.info("Checking if the merged PR matches the finalized state")

    title: str = event.get_title()
    body: str = event.get_body()
    labels: list[str] = event.get_labels_safe()

    semver_lock = SemverLock.load_from_file()
    version: str = str(semver_lock.version)

    expected_labels: list[str] = config.data.pull_request.labels
    expected_title: str = config.data.pull_request.render_title(version=version)

    reasons = []

    # Labels
    missing_labels = set(expected_labels) - set(labels)
    if missing_labels:
        reasons.append(f"Missing labels: {sorted(missing_labels)}")
        reasons.append(f"   All PR labels: {sorted(labels)}")
        reasons.append(f"   Expected labels: {sorted(expected_labels)}")

    # Title
    if title != expected_title:
        reasons.append("Title mismatch:")
        reasons.append(f"   Expected: {expected_title}")
        reasons.append(f"   Actual:   {title}")

    # Body
    if PR_HIDDEN_MARKER not in body:
        reasons.append("Body mismatch:")
        reasons.append("    Hidden marker is not found in the body content.")
        reasons.append("    The body was not generated by semver auto.")

    if reasons:
        logger.info("This is not a finalized process")
        for reason in reasons:
            logger.debug(reason)
        return False

    logger.info("This is a finalized process")

    return True
