name: Publish Release

on:
  push:
    tags:
      - '[0-9*].[0-9*].[0-9*]'
      - '[0-9*].[0-9*].[0-9*]-rc'
  workflow_dispatch: #for testing


jobs:
  production-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Dynamically set environment based on branch
    environment: 'production'

    steps:
      - name: GH Release
        uses: ./.github/actions/gh-release

  staging-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Dynamically set environment based on branch
    environment: 'staging'

    steps:
      - name: GH Release
        uses: ./.github/actions/gh-release