name: Auto Version and Release PR

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: 🧪 Unit tests and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          ./install-task.sh
          task install

      # - name: Run pytest
      #   run: |
      #     source .venv/bin/activate
      #     task test

      - name: Format
        run: |
          source .venv/bin/activate
          task format

      - name: Lint
        run: |
          source .venv/bin/activate
          task lint

      - name: type-check
        run: |
          source .venv/bin/activate
          task type-check

  semver-pr:
    name: 🚀 Run Semver PR Action
    runs-on: ubuntu-latest
    needs: test  # ← Ensures tests pass before running release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run semver-pr action
        run: |
          python main.py \
            --version-files "galaxy.yml" \
            --changelog-file "CHANGELOG.md" \
            --base-branch "dev" \
            --default-bump "patch" \
            --suffix "dev" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --repo "${{ github.repository }}" \
            --branch "${{ github.ref_name }}" \
            --debug